### ISSUE TITLE
Unpack requires a bytes object of length 160

### ISSUE THREAD

**Issue by elitechdatareader** [civic/elitech-datareader#12]
I have an Elitech RC-5 and hope to use your elitech-datareader.

My computer runs Linux Mint Debian Edition 2 - fully updated.

When I plug my device into my PC I get these two new additions to /dev:

/dev/serial
/dev/ttyUSB0

If I do any of these commands I get an error message:

elitech-datareader --command get --page_size=500
/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

elitech-datareader --command get --page_size=500
/dev/serial/by-path/pci-0000\:00\:14.0-usb-0\:6.3\:1.0-port0

elitech-datareader --command get --page_size=500 /dev/ttyUSB0

The error message is:

Traceback (most recent call last):
  File "/usr/local/bin/elitech-datareader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/scripts/elitech_device.py",
line 21, in main
    command_get(args)
  File "/usr/local/lib/python2.7/dist-packages/scripts/elitech_device.py",
line 61, in command_get
    device.get_data(callback=output, page_size=args.page_size)
  File "/usr/local/lib/python2.7/dist-packages/elitech/__init__.py",
line 119, in get_data
    devinfo = self.get_devinfo()
  File "/usr/local/lib/python2.7/dist-packages/elitech/__init__.py",
line 93, in get_devinfo
    res = self._talk(req, DevInfoResponse())
  File "/usr/local/lib/python2.7/dist-packages/elitech/__init__.py",
line 67, in _talk
    response.read(self._ser)
  File "/usr/local/lib/python2.7/dist-packages/elitech/msg.py", line
209, in read
    res)
struct.error: unpack requires a string argument of length 160

What am I doing wrong?

**Comment by civic** [comment]
In the RC-5, this program is still unstable.
What is the software version? v0.9.3?

**Comment by elitechdatareader** [comment]
Yes I am using the latest version.  I have tried installing both python versions (2.7 and 3.4) with pip/pip3 but both produce the same error about a string argument of length 160.

I have checked the requirements list and it seems my system has all the minimum requirements (which were installed with pip).

I have checked my data reader on a Mac and the data can be retrieved with the official software.

**Comment by civic** [comment]
yes. Often my software can't communicate with RC5 correctly.

**Comment by elitechdatareader** [comment]
Can you pinpoint the problem with the information I have given you?  I am happy to try out any new code for you or even try to write it myself but I didn't really understand what the error message was stating.

**Comment by civic** [comment]
that is known issue. It happen same problem on my mac os x. It seems usb-serial communication problem, I think. but, I don't know why.

**Comment by elitechdatareader** [comment]
Strange as my Mac (Yosemite) is under emulation with Virtualbox and it works perfectly.  Will you be able to try to fix this?

**Comment by elitechdatareader** [comment]
Looking at the code it seems this line in msg.py might be the culprit:  res = ser.read(160)

Why is the 160 hard-coded here?  Could we use ser.readline() instead?

(Complete guesses as I have even begun to understand how your magic works!)

**Comment by civic** [comment]
that code means reading 160 bytes of binary data. the length of device Infotmation response message is 160. 
https://github.com/civic/elitech-datareader/blob/master/rc-4-data.md#レスポンス-1

1. Send command to get device information.
2. Read response the device information. it is 160 bytes binary data.
3. unpack binary data.

In RC5. sometimes, The length of response data become zero. I don't know why.

**Comment by elitechdatareader** [comment]
It appears I cannot get any of the commands (eg get, latest, set) to work though (not just the device information).

Has anyone verified this works with a RC-5 ever?

**Comment by elitechdatareader** [comment]
If I use this piece of code:

`import elitech
import datetime
import sys

port = sys.argv[1]
print("PORT: {}".format(port))
device = elitech.Device(port)
device.debug = True
device.init()
device.get_devinfo()`

I get the following output:

PORT: /dev/ttyUSB0

ba length=5
CC 00 0A 00 D6 

ba length=5
CC 00 06 00 D2 

Is this expected?  The "CC 00 0A 00 D6" is from the device.init() command and "CC 00 06 00 D2" is from device.get_devinfo().  How do these numbers help in debugging?

**Comment by elitechdatareader** [comment]
I don't know how to use github properly but I am sure there is some merge command or something I should be doing here.

I've done some hacking and come up with this:

Change line 43 in elitech/__init__.py to:
self._ser = serial.Serial(serial_port, 115200, timeout=3)

To:
self._ser = serial.Serial(serial_port, timeout=None, baudrate=115000, xonxoff=False, rtscts=False, dsrdtr=False)

I think this makes it wait until the data has been obtained.

After I change this every command works as expected.

**Comment by civic** [comment]
Thanks. I tried it. But the problem is not resolved.
Sometimes we succeed, but also at the time of another will fail ( long time no reply.)
I checked on mac os x (10.10.5 Yosemite, not VirtualBox.)

**Comment by elitechdatareader** [comment]
This resolved the problem on the three Debian Linux PCs I tried it on.  It may be that Windows/Mac need to keep 115200.  It is a common problem with Arduinos, Raspberry Pis and pyserial.

[Google](https://encrypted.google.com/search?hl=en&q=pyserial%20115000%20115200)

Perhaps a command line variable could be added to override the default 115200 baudrate with a baudrate of the users choosing?
