### ISSUE TITLE
Update requirements to support latest version of six

### ISSUE THREAD

**Issue by stretch4x4** [civic/elitech-datareader#33]
Hi,

Would it be possible to get a new package built with the requirements update to the latest version of six (1.11.0) or even six>=1.9.0.
I am using this useful package on a cherrypy server to monitor and graph several RC-5 loggers but cherrypy and elitech-datareader require conflicting versions of six.

Thanks

**Comment by civic** [comment]
OK. I'll do it in a few days.

**Comment by stretch4x4** [comment]
Greatly appreciated 👍🏼

________________________________
