### ISSUE TITLE
GSP-6 fails with unknown model no

### ISSUE THREAD

**Issue by freichmann** [civic/elitech-datareader#39]
I have one of these: https://www.elitechonline.co.uk/GSP-6. Only limited operations are supported.

Dev Info works:
> elitech-datareader --command devinfo --encode=utf8 /dev/ttyUSB0 
alarm=AlarmSetting.NONE
current=2019-08-04 12:55:28
delay=0.0
dev_num=
humi_calibration=0.0
humi_lower_limit=10.0
humi_upper_limit=90.0
last_online=2019-08-04 12:54:19
lower_limit=-30.0
model_no=62
rec_count=0
rec_interval=01:00:00
start_time=None
station_no=1
stop_button=StopButton.ENABLE
temp_calibration=0.0
temp_unit=TemperatureUnit.C
tone_set=ToneSet.NONE
upper_limit=85.0
user_info=Kellerabteil
work_sts=WorkStatus.NOT_START

Reading data fails with error:
> elitech-datareader --command get /dev/ttyUSB0 
Traceback (most recent call last):
  File "/usr/bin/elitech-datareader", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/scripts/elitech_device.py", line 23, in main
    command_get(args)
  File "/usr/lib/python3.6/site-packages/scripts/elitech_device.py", line 68, in command_get
    device.get_data(callback=output)
  File "/usr/lib/python3.6/site-packages/elitech/__init__.py", line 134, in get_data
    raise ValueError("Unknowm model_no (%d). can't decide page_size", devinfo.model_no)
ValueError: ("Unknowm model_no (%d). can't decide page_size", 62)

Setting values does not effecitvely write to the device, although no error is written out:
> elitech-datareader --command set -i 15 --user_info="Kühlschrank" /dev/ttyUSB0 
target_station_no=1
rec_interval=00:00:15
upper_limit=85.0
lower_limit=-30.0
update_station_no=1
stop_button=StopButton.ENABLE
delay=0.0
tone_set=ToneSet.NONE
alarm=AlarmSetting.NONE
temp_unit=TemperatureUnit.C
temp_calibration=0.0
humi_upper_limit=90.0
humi_lower_limit=10.0
humi_calibration=0.0
user_info=Kühlschrank
(some ~10s waiting time, no error)

> elitech-datareader --command devinfo --encode=utf8 /dev/ttyUSB0 
alarm=AlarmSetting.NONE
current=2019-08-04 12:57:08
delay=0.0
dev_num=
humi_calibration=0.0
humi_lower_limit=10.0
humi_upper_limit=90.0
last_online=2019-08-04 12:56:53
lower_limit=-30.0
model_no=62
rec_count=0
rec_interval=01:00:00
start_time=None
station_no=1
stop_button=StopButton.ENABLE
temp_calibration=0.0
temp_unit=TemperatureUnit.C
tone_set=ToneSet.NONE
upper_limit=85.0
user_info=Kellerabteil
work_sts=WorkStatus.NOT_START

Model nr, when printed from code, is 62. My attempts for some values for page_size and data_size were not successful (page/data 1000/5). When writing data, the device does not do the typical beep that it does in windows when setting the parameters.

**Comment by spyker0007** [comment]
Hi all, has anybody looked at this issue?
For the previous comment from @freichmann,  if you add --page_size with 500, it returns the following:

```
C:\Users\--\Desktop\elitech-datareader-master>elitech-datareader -c get --page_size=500 COM6
Traceback (most recent call last):
  File "C:\Users\--\AppData\Local\Programs\Python\Python374\Scripts\elitech-datareader-script.py", line 11, in <module>
    load_entry_point('elitech-datareader==1.0.5', 'console_scripts', 'elitech-datareader')()
  File "C:\Users\--\AppData\Local\Programs\Python\Python374\lib\site-packages\scripts\elitech_device.py", line 23, in main
    command_get(args)
  File "C:\Users\--\AppData\Local\Programs\Python\Python374\lib\site-packages\scripts\elitech_device.py", line 66, in command_get
    device.get_data(callback=output, page_size=args.page_size)
  File "C:\Users\--\AppData\Local\Programs\Python\Python374\lib\site-packages\elitech\__init__.py", line 136, in get_data
    page = int(math.ceil(header.rec_count * data_size / float(page_size)))
UnboundLocalError: local variable 'data_size' referenced before assignment
```
I've edited __init__.py to initialize data_size variable a start value of 0, rerun the command, no error and nothing happens.

Setting the baud rate and timeout has no effect: --ser_baudrate 115200 --ser_timeout=10.
 I believe that the ValueError: ("Unknowm model_no (%d). can't decide page_size", 62) it is because, as per __init.py__, the model of the GSP-6 is not referenced directly; I don't know yet if the GSP-6 is compatible with RC-4 or 5, but the code doesn't include it:
```
        devinfo = self.get_devinfo()
        header = self.get_data_header(devinfo.station_no)
        if page_size is None:
            if devinfo.model_no == 40: # RC-4
                page_size = 100
                data_size = 1
            elif devinfo.model_no == 42: #RC-4HC
                page_size = 200
                data_size = 2
            elif devinfo.model_no == 50: #RC-5
                page_size = 500
                data_size = 1
            else:
                raise ValueError("Unknowm model_no (%d). can't decide page_size", devinfo.model_no)
```
Is it possible to know if the GSP-6 is compatible?

Best regards,

**Comment by spyker0007** [comment]
Sorry, in last post I didn't mention on what platform I was working on: Windows 10, Python 3.7.4.

UPDATE:
I have done a little Frankestein: added info of the device (cloned from RC-5 entry in `__init.py:__`)

![image](https://user-images.githubusercontent.com/91545681/135167551-cb581a12-986b-45a3-93c5-55e3c4dac773.png)

So far it seems to be working:
![image](https://user-images.githubusercontent.com/91545681/135167691-d017595e-6f33-4599-ab75-6b059a25760e.png)
![image](https://user-images.githubusercontent.com/91545681/135167784-11992c36-f586-4e45-a8f0-512d72a3c631.png)

Of course, it will be much better if these RC-5 parameters could be verified as usable for the GSP-6

**Comment by civic** [comment]
Thank you for your information, @spyker0007. 
Please post a pull request if you can. I will check and merge it.

**Comment by civic** [comment]
#41
