### ISSUE TITLE
RC5 compatibility

### ISSUE THREAD

**Issue by gravatite** [civic/elitech-datareader#8]
I have a couple of the RC5 data loggers, and this software works almost perfectly with them.  The commands to set the time and change settings appear to work fine, the only problem is with downloading the data records.  After a little debugging, it looks like the RC5 returns 500 entries per page instead of 100, so I modified the get_data function to use 500 and it works great.  Since the change between models is so small, it would be nice if the code could auto-detect which model it is and use the correct page size.  Alternatively, instead of assuming there are 100 records, it could simply read all data returned after making a request, subtract 2 for the checksum and divide by 2 to get the number of records returned in that page request.  Then it would auto-adjust for the page size and simply stop requesting pages when it's retrieved the total record count (or more since the device could still be logging).  Option 3 might be to simply have a command line switch for the RC5 that tells the software to expect the larger page sizes.

**Comment by civic** [comment]
Thank you for the report of RC5! :+1: 
I'll support RC5 data logger. I have just bought a RC5.

**Comment by JoanneThomas** [comment]
Just joined to say "thank you" to both of you. I'm making use of a couple of RC-5s at work and @gravitate's comment was what I needed to get things working a little better and none of it would have been possible without @civic's code. So: thank you.

**Comment by civic** [comment]
@gravatite I got a RC5. 
USB-Serial driver of RC5 is different to RC4. I found this driver for macosx. http://www.wch.cn/download/CH341SER_MAC_ZIP.html. but It is a little unstable. Do you use RC-5 on Windows? And how did you get the USB-Serial driver for RC-5?

**Comment by gravatite** [comment]
I use Linux, so no driver issues.  It pops right up as a serial device without any additional drivers or settings.

**Comment by civic** [comment]
I implemented RC5 support. Maybe 4th byte of devinfo might be model Number. My RC4 returns 0x28, and RC5 returns 0x32. it choice page size on RC4/RC5.
