### ISSUE TITLE
Calling just the latest reading

### ISSUE THREAD

**Issue by JoanneThomas** [civic/elitech-datareader#9]
Hi @civic,

How easy would it be to add a command to the code to allow retrieval of just the last recorded temperature?

By way of explanation:
We're using URC-5s as a cheap way of remotely keeping an eye on temperature in server rooms. As a data logger, it means we can continue to record the temperature even if the servers go down so we can check how bad things get in the event of a power outage (currently more common than we'd like) by downloading the recorded data. However, it would be good to have the data available on our monitoring software (Zabbix) so we can compare numbers easily.

Using your code, it's possible to cut the latest value from the data so
`elitech-device.py --command get /dev/ttyUSB0`
becomes
`elitech-device.py --command get /dev/ttyUSB0 | tail -1 | awk '{print $4}'`

However, this is going to become cumbersome as more records accumulate and will timeout as a request in Zabbix.

Just thought I'd ask as I haven't got a clue where to start myself!

**Comment by civic** [comment]
@JoanneThomas 
It's easy.

https://github.com/civic/elitech-datareader/blob/master/elitech/__init__.py#L128

Here the code is an implementation of the command 'get'. 

1. get device information. 
2. The total number of data you can see in get_header. 
3. Repeat one page data at a time


I think that in the next version may be to create a new command 'get_latest'.
However, communication in the RC-5 is so much slower than the RC-4. So, I do not know either prevent a time-out.

**Comment by JoanneThomas** [comment]
Thanks :) I shall have a look at that!

**Comment by civic** [comment]
add command latest. v0.9.3

```
$ elitech-datareader --command latest /dev/tty.SLAB_USBtoUART
6   2015-06-07 13:54:26 25.2

$ elitech-datareader --command latest --only-value /dev/tty.SLAB_USBtoUART
25.2
```

**Comment by JoanneThomas** [comment]
Nice work, @civic, thank you!

Just so you know, the --only-value command is actually encoded as --value_only. The command as given above gives:

```
# elitech-datareader --command latest --only-value /dev/ttyUSB0
 usage: description elitech RC-4 data reader [-h]
                                             [-c {init,get,latest,simple-set,set,devinfo,clock,raw}]
                                             [-i INTERVAL]
                                             [--upper_limit UPPER_LIMIT]
                                             [--lower_limit LOWER_LIMIT]
                                             [--station_no STATION_NO]
                                             [--stop_button {y,n}]
                                             [--delay {0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0}]
                                             [--tone_set {y,n}]
                                             [--alarm {x,3,10}]
                                             [--temp_unit {C,F}]
                                             [--temp_calibration TEMP_CALIBRATION]
                                             [--time TIME] [--dev_num DEV_NUM]
                                             [--user_info USER_INFO]
                                             [--page_size PAGE_SIZE]
                                             [--req REQ] [--res_len RES_LEN]
                                             [--value_only]
                                             serial_port
 description elitech RC-4 data reader: error: unrecognized arguments: --only-value
```

But it works great if corrected to the command given in the error message!

**Comment by civic** [comment]
@JoanneThomas Thanks, I fixed the text.
